### ISSUE TITLE
Problema ao gerar o executavel.

### ISSUE THREAD

**Issue by Amauri-Souza** [marcellobatiista/KL-Bot#1]
eu coloquei o caminho da pasta tudo certinho mais no terminal aparece assim "bash: pyinstaller: command not found", tentei já de varias forma mais não tive nenhum êxito.

**Comment by marcellobatiista** [comment]
python -m PyInstaller --noconfirm --onefile --windowed --add-data "C:/CAMINHO/PARA/PASTA/system;system/" --add-data "C:/CAMINHO/PARA/PASTA/forms;forms/"  "C:/CAMINHO/PARA/ARQUIVO/main.py"
